### ISSUE TITLE
Commit ab03c835d1fcb2e13b896f54797e9007ed3de838 broke frontend compilation (previous commit works fine)

### ISSUE THREAD

**Issue by loxal** [Kotlin/kotlin-fullstack-sample#11]
> ✘-1 ~/Downloads/kotlin-fullstack-sample [master|✚ 1…5] 
> 18:54 $ ./gradlew frontend:run
> :frontend:npm-preunpack UP-TO-DATE
> :frontend:npm-configure UP-TO-DATE
> :frontend:npm-install
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for kotlin@1.1.1
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget 
> npm ERR! notarget It was specified as a dependency of 'frontend'
> npm ERR! notarget 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/alex/.npm/_logs/2017-06-12T16_54_58_426Z-debug.log
> :frontend:npm-install FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':frontend:npm-install'.
> > npm install failed (exit code = 1)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 5.496 secs

**Comment by dcc635** [comment]
I get this error too. It seems that it's looking for kotlin@1.1.1, but only 1.1.0 exists on [npm](https://www.npmjs.com/package/kotlin). Relevant error log:

```
1603 http fetch GET 304 https://registry.npmjs.org/kotlin 52ms (from cache)
1604 silly fetchPackageMetaData error for kotlin@1.1.1 No matching version found for kotlin@1.1.1
1605 http fetch GET 404 https://registry.npmjs.org/kotlin-test-js 380ms
1606 silly fetchPackageMetaData error for kotlin-test-js@1.1.1 404 Not Found: kotlin-test-js@1.1.1
1607 http fetch GET 404 https://registry.npmjs.org/kotlinx-html-js 449ms
1608 silly fetchPackageMetaData error for kotlinx-html-js@1.1.0 404 Not Found: kotlinx-html-js@1.1.0
1609 verbose type version
1610 verbose stack kotlin: No matching version found for kotlin@1.1.1
```

**Comment by mkulak** [comment]
I have the same problem: cannot run frontend at all.I tried to change 1.1.1 to 1.1.0, but this doesn't help.

**Comment by OscarScholten** [comment]
Similar problem here, when I switch back to 1.1.0, it fails on kotlin-test-js and kotlinx-html-js who both doth have any info published:

1578 silly pacote version manifest for kotlin@1.1.0 fetched in 14ms
1579 silly resolveWithNewModule kotlin@1.1.0 checking installable status
1580 http fetch GET 404 https://registry.npmjs.org/kotlin-test-js 1043ms
1581 silly fetchPackageMetaData error for kotlin-test-js@1.1.0 404 Not Found: kotlin-test-js@1.1.0
1582 http fetch GET 404 https://registry.npmjs.org/kotlinx-html-js 1438ms
1583 silly fetchPackageMetaData error for kotlinx-html-js@1.1.0 404 Not Found: kotlinx-html-js@1.1.0
1584 verbose stack Error: 404 Not Found: kotlin-test-js@1.1.0
1584 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
1584 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1584 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
1584 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
1584 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1584 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1584 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
1584 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
1584 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
1584 verbose stack     at runCallback (timers.js:800:20)
1584 verbose stack     at tryOnImmediate (timers.js:762:5)
1584 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
1585 verbose cwd /Users/oscar1/projects/personal/kotlin/kotlin-fullstack-sample/frontend/build
1586 verbose Darwin 16.6.0
1587 verbose argv "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/bin/npm" "install"
1588 verbose node v8.1.2
1589 verbose npm  v5.0.3
1590 error code E404
1591 error 404 Not Found: kotlin-test-js@1.1.0
1592 verbose exit [ 1, true ]

**Comment by czeidler** [comment]
Yes, kotlinx-html-js seems to be gone from npmjs.com. Any idea what to do?

**Comment by mkulak** [comment]
Can somebody resubmit it?

**Comment by cy6erGn0m** [comment]
Doesn't it work with latest version?

**Comment by mkulak** [comment]
@cy6erGn0m wow, it actually works now!
I think we can close this.

**Comment by loxal** [comment]
works fine now 👍
