### ISSUE TITLE
how to upgrade to EAP 1.1.4

### ISSUE THREAD

**Issue by andrewarrow** [Kotlin/kotlin-fullstack-sample#18]
between this file `https://github.com/Kotlin/kotlin-fullstack-sample/blob/master/build.gradle` and `https://github.com/Kotlin/kotlin-fullstack-sample/blob/master/frontend/build.gradle` there are 12 versions:

1. ext.kotlin_version
2. kotlin-gradle-plugin
3. kotlin-frontend-plugin
4. html_version
5. ktor_version
6. squash_version
7. kotlin-stdlib-js
8. kotlin-test-js
9. kotlinx-html-js
10. kotlinx-html-js (replaceVersion)
11. kotlinx-html-shared (replaceVersion)
12. kotlin-js-library (replaceVersion)

I'm trying to update to EAP 1.1.4 but it's very confusing which versions to update and get it to still build. Can anyone make a PR with this fullstack sample using the latest and greatest version?

**Comment by cy6erGn0m** [comment]
It's not so easy for now as many things need to be in-sync. At least custom repositories need to be added,`ext.kotlin_version` and `kotlinx-html-js` should be amended.
