### ISSUE TITLE
unable to start forntend

### ISSUE THREAD

**Issue by oshai** [Kotlin/kotlin-fullstack-sample#7]
When running:
./gradlew frontend:run
I got this error:
webpack-dev-server exited with exit code 1, 
...
.../kotlin-fullstack-sample/frontend/build/node_modules/webpack/lib/webpack.js:7
const Compiler = require("./Compiler");
^^^^^
SyntaxError: Use of const in strict mode.

Any help will be appreciated.

**Comment by cy6erGn0m** [comment]
Looks like you have some unusual nodejs version or something in your environment? don't you have any special settings?

**Comment by cy6erGn0m** [comment]
Doesn't this answer help to resolve your issue? http://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode

**Comment by oshai** [comment]
Thanks! that fixed it.
